### ISSUE TITLE
Single file version

### ISSUE THREAD

**Issue by nightfury7** [Zaseth/ByteArray.js#3]
Do you have a single file version? You can easily make a script to compile one with gulp. I can contribute that if you want.

**Comment by Zaseth** [comment]
Hello.

Putting everything together will reduce the performance heavily. I've been experimenting with single file versions and ByteArray in general for quite a while now and I noticed that the current layout works the best. Another reason why I made the layout like this and separated the AMF libraries is for people to understand what is exactly going on in what file. This repository is not just meant for Javascript developers, but also developers coming from Actionscript and Flex. With every file being separated, anyone can make changes to customize things to their needs with ease. And having a single file version and a separated file version is just making a mess for pushing updates. I understand that having a single file is cleaner, but it's not the case for this library.

**Comment by nightfury7** [comment]
No, I don't think you understood me. You can have the repo exactly like
this. There is a compile time tool called gulp, which merges all your
files. It makes it easier to deploy a single file. This technique is used
by all major libraries like jQuery, bootstrap, etc... It's how they have a
multiple file repo but ship only a single file. No way performance is
affected either.

**Comment by Zaseth** [comment]
I have never worked with it and if I ever wanted to, I'll do it myself.

**Comment by nightfury7** [comment]
Wow. So friendly. You gotta learn to work with other people and at least be
polite, or you'll scare away all the potential contributors. Good luck
finding help.
